### PR TITLE
add hex_* params to escape special chars

### PR DESCRIPTION
**Pull request by manuel-rubio**
These params are based on the PHP json_encode function.

### CODE REVIEW

**Comment by sile** [comment]
I am unfamiliar with PHP. So I would appreciate it if you could explain why these options are needed.

**Comment by manuel-rubio** [comment]
I'm coding a PHP interpreter on Erlang: https://github.com/altenwald/ephp , and writing the JSON library in this https://github.com/altenwald/ephp_json I realize there are options available in PHP that are not available in jsone.

For example from the example ( https://github.com/altenwald/ephp_json/blob/master/test/code/02_json_encode.php ):

```php
echo "Normal: ",  json_encode($a), "\n";
echo "Tags: ",    json_encode($a, JSON_HEX_TAG), "\n";
echo "Apos: ",    json_encode($a, JSON_HEX_APOS), "\n";
echo "Quot: ",    json_encode($a, JSON_HEX_QUOT), "\n";
echo "Amp: ",     json_encode($a, JSON_HEX_AMP), "\n";
echo "Unicode: ", json_encode($a, JSON_UNESCAPED_UNICODE), "\n";
echo "All: ",     json_encode($a, JSON_HEX_TAG | JSON_HEX_APOS | JSON_HEX_QUOT | JSON_HEX_AMP | JSON_UNESCAPED_UNICODE), "\n\n";
```

That give us ( https://github.com/altenwald/ephp_json/blob/master/test/code/02_json_encode.out ):

```
Normal: ["<foo>","'bar'","\"baz\"","&blong&","\u00e9"]
Tags: ["\u003Cfoo\u003E","'bar'","\"baz\"","&blong&","\u00e9"]
Apos: ["<foo>","\u0027bar\u0027","\"baz\"","&blong&","\u00e9"]
Quot: ["<foo>","'bar'","\u0022baz\u0022","&blong&","\u00e9"]
Amp: ["<foo>","'bar'","\"baz\"","\u0026blong\u0026","\u00e9"]
Unicode: ["<foo>","'bar'","\"baz\"","&blong&","é"]
All: ["\u003Cfoo\u003E","\u0027bar\u0027","\u0022baz\u0022","\u0026blong\u0026","é"]
```

With `tag` all of the `<` and `>` and parsed as special codes, with `amp` the ampersand (&) is converted, with `apos` the apostrophe (') and with `quote` the double quotes (").

In that way, you can get:

```erlang
A = [<<"<foo>">>, <<"'bar'">>, <<"\"baz\"">>, <<"&blong&">>, <<16#c3a9:16>>],
io:format("Normal: ~s~n",  [jsone:encode(A)]),
io:format("Tags: ~s~n",  [jsone:encode(A, [hex_tag]),
io:format("Apos: ~s~n",  [jsone:encode(A, [hex_apos]),
io:format("Quot: ~s~n",  [jsone:encode(A, [hex_quote]),
io:format("Amp: ~s~n",  [jsone:encode(A, [hex_amp]),
io:format("Unicode: ~s~n",  [jsone:encode(A, [native_utf8]),
io:format("All: ~s~n",  [json_encode(A, [hex_tag, hex_apos, hex_quote, hex_amp, native_utf8]).
```

And obtain the same result as with PHP json function.

**Comment by pichi** [comment]
I don't get it why jsone should mimic some PHP behavior and jeopardize the performance in progress. If you need JSON embedded in HTML or URL or whatever you should do proper escaping for each use.

**Comment by manuel-rubio** [comment]
@pichi I get the point jsone was developped with maximum performance in mind, but in my opinion my changes are not jeopardizing the performance and not, I cannot do that modifications neither after or before the transformation. If I try to do them before, the "\" is translated as "\\" and parsing JSON or do the parsing string by string is not a solution at all so, the change after is not an option for me.

Anyway without benchmark tests we cannot know if the performance is decreased or not.

**Comment by pichi** [comment]
@manuel-rubio 

> Anyway without benchmark tests we cannot know if the performance is decreased or not.

Right. Just do it!

**Comment by sile** [comment]
In addition to the @pichi's opinion (i.e., performance concerns), I would like to consider whether there is a more generic way to achieve the same goal, rather than directly importing the functionalities that exist in other languages (or libraries).
(i.e., Adding an option which allows escaping arbitrary characters)

**Comment by pichi** [comment]
You can transform all your strings using your own transformation, replace then using `json_term` and then use `jsone` for the rest.
See https://github.com/sile/jsone/blob/master/doc/jsone.md#type-json_term

**Comment by manuel-rubio** [comment]
@pichi your solution could be a way to solve my issue... anyway, if you want this modification, I did the performance test and looks like it's not much different from the original one (keep in mind micro-seconds from one test to the other could be a bit different and sometimes the new modification is better because of that):

```
# Non-HiPE

## EncoderBench                         Original             Modified
maps (jsone)                   100000   22.99 µs/op          21.28 µs/op
lists (jsone)                   10000   282.05 µs/op         274.75 µs/op
strings (jsone)                  1000   1010.67 µs/op        1006.03 µs/op
string escaping (jsone)          1000   1307.23 µs/op        1350.14 µs/op
jsone                            1000   2658.68 µs/op        2583.45 µs/op
jsone (pretty)                    500   3062.46 µs/op        3224.02 µs/op

## ParserBench
UTF-8 unescaping (jsone)         5000   463.91 µs/op         472.90 µs/op
jsone                            1000   2163.55 µs/op        2300.10 µs/op

# HiPE

## EncoderBench
maps (jsone)                   500000   7.60 µs/op           8.35 µs/op
lists (jsone)                   20000   83.49 µs/op          82.64 µs/op
string escaping (jsone)          5000   365.24 µs/op         415.73 µs/op
strings (jsone)                  5000   411.95 µs/op         547.75 µs/op
jsone                            2000   929.28 µs/op         967.65 µs/op
jsone (pretty)                   2000   1156.46 µs/op        993.82 µs/op

## ParserBench
UTF-8 unescaping (jsone)        10000   129.19 µs/op         129.27 µs/op
jsone                            2000   767.04 µs/op         819.40 µs/op
```

**Comment by pichi** [comment]
I see 14% slower string escaping and 33% slower strings in HiPE. I would not call it _not much different_. It is expected an effect of the PR. There is 9% drop in performance of maps encoding which could be expected as well when you consider each map key is a string. There is also possible add this feature as a feature added as macro and let it compile only if some definition set for purpose of your project.

**Comment by manuel-rubio** [comment]
@pichi I think that's a good idea. I'll change the code to use only the modifications when the specific modificator will be passed for the compilation.

**Comment by sile** [comment]
Let me close this PR as there are no activities for a long time.

**Pull request closed without merging**
